# register
GET https://imoocqa.gugujiankong.com/api/account/register?mobile=15822223334&nickname=ionicman&password=12345678 HTTP/1.1
###

# login
GET https://imoocqa.gugujiankong.com/api/account/login?mobile=15822223333&password=12345678 HTTP/1.1
