# register
GET https://imoocqa.gugujiankong.com/api/account/register?mobile=15822223334&nickname=ionicman&password=12345678 HTTP/1.1
###

# login
GET https://imoocqa.gugujiankong.com/api/account/login?mobile=15822223333&password=12345678 HTTP/1.1
###

# get user info
GET https://imoocqa.gugujiankong.com/api/account/userinfo?userid=5ce93420647eb40598e141a4 HTTP/1.1
###


# update nickname info
GET https://imoocqa.gugujiankong.com/api/account/updatenickname?userid=5ce93420647eb40598e141a4&nickname=Houdini HTTP/1.1
###